-- AlterTable
ALTER TABLE "informations" ALTER COLUMN "bio" DROP NOT NULL,
ALTER COLUMN "avatar_url" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "facebook_url" DROP NOT NULL,
ALTER COLUMN "date_of_birth" DROP NOT NULL,
ALTER COLUMN "class_name" DROP NOT NULL,
ALTER COLUMN "grade_code" DROP NOT NULL,
ALTER COLUMN "grade_name" DROP NOT NULL,
ALTER COLUMN "cover_image_url" DROP NOT NULL;
